// examples/react/basic/TodoList.tsx
import React, { useState, useEffect, useCallback, useMemo } from 'react';

/**
 * Prompt: Componente React funcional para lista de tareas con funcionalidad CRUD
 * Debe usar hooks modernos, estado local, funciones memoizadas y renders optimizados
 * Incluir funciones de agregar, completar, eliminar, editar y filtrar tareas
 */

interface Todo {
  id: string;
  text: string;
  completed: boolean;
  createdAt: Date;
}

type FilterType = 'all' | 'pending' | 'completed';

interface FilterOption {
  label: string;
  value: FilterType;
}

const TodoList: React.FC = () => {
  // Prompt: Estados principales usando useState
  // Incluir lista de tareas, filtro activo, tarea en edición y texto de nueva tarea
  const [todos, setTodos] = useState<Todo[]>([]);
  const [filter, setFilter] = useState<FilterType>('all');
  const [editingTodo, setEditingTodo] = useState<Todo | null>(null);
  const [newTaskText, setNewTaskText] = useState('');

  // Prompt: useEffect para inicializar datos de ejemplo al montar componente
  useEffect(() => {
    const sampleTodos: Todo[] = [
      {
        id: generateId(),
        text: 'Aprender React con GitHub Copilot',
        completed: true,
        createdAt: new Date(Date.now() - 86400000), // Ayer
      },
      {
        id: generateId(),
        text: 'Crear componente de perfil de usuario',
        completed: false,
        createdAt: new Date(Date.now() - 3600000), // Hace 1 hora
      },
      {
        id: generateId(),
        text: 'Implementar hooks personalizados',
        completed: false,
        createdAt: new Date(), // Ahora
      },
    ];
    setTodos(sampleTodos);
  }, []);

  /**
   * Prompt: Función para generar ID único usando timestamp y random
   * Debe retornar string único para identificar tareas
   */
  const generateId = (): string => {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
  };

  /**
   * Prompt: Opciones de filtro memoizadas con useMemo
   * Debe incluir todas, pendientes y completadas
   */
  const filterOptions: FilterOption[] = useMemo(() => [
    { label: '📋 Todas', value: 'all' },
    { label: '⏳ Pendientes', value: 'pending' },
    { label: '✅ Completadas', value: 'completed' },
  ], []);

  /**
   * Prompt: Tareas filtradas usando useMemo para optimizar renders
   * Debe filtrar según el tipo de filtro activo
   */
  const filteredTodos = useMemo(() => {
    switch (filter) {
      case 'completed':
        return todos.filter(todo => todo.completed);
      case 'pending':
        return todos.filter(todo => !todo.completed);
      default:
        return todos;
    }
  }, [todos, filter]);

  /**
   * Prompt: Estadísticas calculadas con useMemo
   * Debe incluir total, completadas y pendientes
   */
  const stats = useMemo(() => ({
    total: todos.length,
    completed: todos.filter(todo => todo.completed).length,
    pending: todos.filter(todo => !todo.completed).length,
  }), [todos]);

  /**
   * Prompt: Función para agregar nueva tarea usando useCallback
   * Debe validar texto no vacío y agregar tarea al inicio de la lista
   */
  const addTask = useCallback(() => {
    if (newTaskText.trim()) {
      const newTodo: Todo = {
        id: generateId(),
        text: newTaskText.trim(),
        completed: false,
        createdAt: new Date(),
      };
      setTodos(prev => [newTodo, ...prev]);
      setNewTaskText('');
    }
  }, [newTaskText]);

  /**
   * Prompt: Función para alternar estado completado usando useCallback
   * Debe encontrar tarea por ID y cambiar su estado
   */
  const toggleTask = useCallback((id: string) => {
    setTodos(prev => prev.map(todo =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    ));
  }, []);

  /**
   * Prompt: Función para eliminar tarea usando useCallback
   * Debe filtrar array removiendo tarea con ID específico
   */
  const deleteTask = useCallback((id: string) => {
    setTodos(prev => prev.filter(todo => todo.id !== id));
  }, []);

  /**
   * Prompt: Función para iniciar edición usando useCallback
   * Debe establecer tarea en estado de edición
   */
  const startEditing = useCallback((todo: Todo) => {
    setEditingTodo({ ...todo });
  }, []);

  /**
   * Prompt: Función para guardar edición usando useCallback
   * Debe actualizar texto de la tarea y salir del modo edición
   */
  const saveEdit = useCallback((newText: string) => {
    if (editingTodo && newText.trim()) {
      setTodos(prev => prev.map(todo =>
        todo.id === editingTodo.id 
          ? { ...todo, text: newText.trim() }
          : todo
      ));
      setEditingTodo(null);
    }
  }, [editingTodo]);

  /**
   * Prompt: Función para cancelar edición usando useCallback
   * Debe limpiar estado de edición sin guardar cambios
   */
  const cancelEdit = useCallback(() => {
    setEditingTodo(null);
  }, []);

  /**
   * Prompt: Función para manejar tecla Enter en inputs
   * Debe ejecutar acción correspondiente según el contexto
   */
  const handleKeyPress = useCallback((
    e: React.KeyboardEvent,
    action: () => void
  ) => {
    if (e.key === 'Enter') {
      action();
    }
  }, []);

  /**
   * Prompt: Función para obtener mensaje cuando no hay tareas
   * Debe retornar mensaje contextual según el filtro activo
   */
  const getEmptyMessage = useCallback((): string => {
    switch (filter) {
      case 'completed':
        return '🎉 ¡No hay tareas completadas aún!';
      case 'pending':
        return '✨ ¡Todas las tareas están completadas!';
      default:
        return '📝 No hay tareas. ¡Agrega una nueva tarea para comenzar!';
    }
  }, [filter]);

  // Prompt: Estilos CSS-in-JS organizados por componente
  const styles: { [key: string]: React.CSSProperties } = {
    container: {
      maxWidth: '800px',
      margin: '20px auto',
      padding: '20px',
      backgroundColor: '#f5f5f5',
      borderRadius: '8px',
      fontFamily: 'Arial, sans-serif',
    },
    title: {
      textAlign: 'center',
      color: '#333',
      marginBottom: '20px',
    },
    addTaskForm: {
      display: 'flex',
      marginBottom: '20px',
      gap: '10px',
    },
    taskInput: {
      flex: 1,
      padding: '10px',
      border: '1px solid #ddd',
      borderRadius: '4px',
      fontSize: '14px',
    },
    filters: {
      display: 'flex',
      gap: '10px',
      marginBottom: '20px',
    },
    stats: {
      backgroundColor: 'white',
      padding: '10px',
      borderRadius: '4px',
      marginBottom: '20px',
      textAlign: 'center',
    },
    taskList: {
      backgroundColor: 'white',
      borderRadius: '4px',
      overflow: 'hidden',
    },
    taskItem: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '15px',
      borderBottom: '1px solid #eee',
      transition: 'background-color 0.2s',
    },
    taskItemCompleted: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '15px',
      borderBottom: '1px solid #eee',
      transition: 'background-color 0.2s',
      opacity: 0.7,
      backgroundColor: '#f1f3f4',
    },
    taskContent: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      flex: 1,
    },
    taskText: {
      flex: 1,
      fontSize: '16px',
    },
    taskTextCompleted: {
      flex: 1,
      fontSize: '16px',
      textDecoration: 'line-through',
    },
    taskDate: {
      color: '#6c757d',
      fontSize: '12px',
    },
    taskActions: {
      display: 'flex',
      gap: '5px',
    },
    emptyState: {
      textAlign: 'center',
      padding: '40px',
      color: '#6c757d',
      fontStyle: 'italic',
    },
    modalOverlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
    },
    modal: {
      backgroundColor: 'white',
      padding: '20px',
      borderRadius: '8px',
      minWidth: '300px',
    },
    modalActions: {
      display: 'flex',
      gap: '10px',
      marginTop: '15px',
      justifyContent: 'flex-end',
    },
    button: {
      padding: '8px 16px',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      fontSize: '14px',
    },
    buttonPrimary: { backgroundColor: '#007bff', color: 'white' },
    buttonSuccess: { backgroundColor: '#28a745', color: 'white' },
    buttonSecondary: { backgroundColor: '#6c757d', color: 'white' },
    buttonDanger: { backgroundColor: '#dc3545', color: 'white' },
    buttonFilter: { backgroundColor: '#e9ecef', color: '#495057' },
    buttonFilterActive: { backgroundColor: '#007bff', color: 'white' },
    buttonSmall: { padding: '4px 8px', fontSize: '12px' },
  };

  return (
    <div style={styles.container}>
      <h2 style={styles.title}>📝 Lista de Tareas con GitHub Copilot</h2>
      
      {/* Formulario para agregar tarea */}
      <div style={styles.addTaskForm}>
        <input
          type="text"
          placeholder="Nueva tarea..."
          value={newTaskText}
          onChange={(e) => setNewTaskText(e.target.value)}
          onKeyPress={(e) => handleKeyPress(e, addTask)}
          style={styles.taskInput}
        />
        <button
          onClick={addTask}
          style={{ ...styles.button, ...styles.buttonPrimary }}
        >
          ➕ Agregar
        </button>
      </div>

      {/* Filtros */}
      <div style={styles.filters}>
        {filterOptions.map((filterOption) => (
          <button
            key={filterOption.value}
            onClick={() => setFilter(filterOption.value)}
            style={{
              ...styles.button,
              ...(filter === filterOption.value ? styles.buttonFilterActive : styles.buttonFilter),
            }}
          >
            {filterOption.label}
          </button>
        ))}
      </div>

      {/* Estadísticas */}
      <div style={styles.stats}>
        <p>
          📊 Total: {stats.total} | 
          ✅ Completadas: {stats.completed} | 
          ⏳ Pendientes: {stats.pending}
        </p>
      </div>

      {/* Lista de tareas */}
      {filteredTodos.length > 0 ? (
        <div style={styles.taskList}>
          {filteredTodos.map((todo) => (
            <div
              key={todo.id}
              style={todo.completed ? styles.taskItemCompleted : styles.taskItem}
            >
              <div style={styles.taskContent}>
                <input
                  type="checkbox"
                  checked={todo.completed}
                  onChange={() => toggleTask(todo.id)}
                  style={{ transform: 'scale(1.2)' }}
                />
                <span style={todo.completed ? styles.taskTextCompleted : styles.taskText}>
                  {todo.text}
                </span>
                <small style={styles.taskDate}>
                  {todo.createdAt.toLocaleString()}
                </small>
              </div>
              <div style={styles.taskActions}>
                <button
                  onClick={() => startEditing(todo)}
                  disabled={todo.completed}
                  style={{
                    ...styles.button,
                    ...styles.buttonSmall,
                    ...styles.buttonSecondary,
                    opacity: todo.completed ? 0.6 : 1,
                  }}
                >
                  ✏️
                </button>
                <button
                  onClick={() => deleteTask(todo.id)}
                  style={{
                    ...styles.button,
                    ...styles.buttonSmall,
                    ...styles.buttonDanger,
                  }}
                >
                  🗑️
                </button>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div style={styles.emptyState}>
          <p>{getEmptyMessage()}</p>
        </div>
      )}

      {/* Modal de edición */}
      {editingTodo && (
        <div style={styles.modalOverlay} onClick={cancelEdit}>
          <div style={styles.modal} onClick={(e) => e.stopPropagation()}>
            <h3>Editar Tarea</h3>
            <input
              type="text"
              defaultValue={editingTodo.text}
              onKeyPress={(e) => {
                if (e.key === 'Enter') {
                  const target = e.target as HTMLInputElement;
                  saveEdit(target.value);
                }
              }}
              style={{
                width: '100%',
                padding: '8px',
                border: '1px solid #ddd',
                borderRadius: '4px',
                margin: '10px 0',
              }}
              autoFocus
            />
            <div style={styles.modalActions}>
              <button
                onClick={() => {
                  const input = document.querySelector(
                    '.modal input'
                  ) as HTMLInputElement;
                  if (input) saveEdit(input.value);
                }}
                style={{ ...styles.button, ...styles.buttonSuccess }}
              >
                💾 Guardar
              </button>
              <button
                onClick={cancelEdit}
                style={{ ...styles.button, ...styles.buttonSecondary }}
              >
                ❌ Cancelar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default TodoList;

// examples/angular/basic/todo-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable, BehaviorSubject } from 'rxjs';
import { map, filter } from 'rxjs/operators';

/**
 * Prompt: Componente Angular para lista de tareas con funcionalidad CRUD
 * Debe usar RxJS observables, filtros y manejo de estado reactivo
 * Incluir funciones de agregar, completar, eliminar y filtrar tareas
 */
@Component({
  selector: 'app-todo-list',
  template: `
    <div class="todo-container">
      <h2>📝 Lista de Tareas con GitHub Copilot</h2>
      
      <!-- Formulario para agregar tarea -->
      <div class="add-task-form">
        <input 
          #taskInput
          type="text" 
          placeholder="Nueva tarea..." 
          class="task-input"
          (keyup.enter)="addTask(taskInput.value); taskInput.value=''"
        >
        <button 
          (click)="addTask(taskInput.value); taskInput.value=''"
          class="btn btn-primary"
        >
          ➕ Agregar
        </button>
      </div>

      <!-- Filtros -->
      <div class="filters">
        <button 
          *ngFor="let filter of filterOptions" 
          (click)="setFilter(filter.value)"
          [class.active]="currentFilter === filter.value"
          class="btn btn-filter"
        >
          {{ filter.label }}
        </button>
      </div>

      <!-- Estadísticas -->
      <div class="stats">
        <p>
          📊 Total: {{ (todos$ | async)?.length || 0 }} | 
          ✅ Completadas: {{ completedCount$ | async }} | 
          ⏳ Pendientes: {{ pendingCount$ | async }}
        </p>
      </div>

      <!-- Lista de tareas -->
      <div class="task-list">
        <div 
          *ngFor="let todo of filteredTodos$ | async; trackBy: trackByTodo" 
          class="task-item"
          [class.completed]="todo.completed"
        >
          <div class="task-content">
            <input 
              type="checkbox" 
              [checked]="todo.completed"
              (change)="toggleTask(todo.id)"
              class="task-checkbox"
            >
            <span 
              class="task-text"
              [class.line-through]="todo.completed"
            >
              {{ todo.text }}
            </span>
            <small class="task-date">{{ todo.createdAt | date:'short' }}</small>
          </div>
          <div class="task-actions">
            <button 
              (click)="editTask(todo)"
              class="btn btn-sm btn-secondary"
              [disabled]="todo.completed"
            >
              ✏️
            </button>
            <button 
              (click)="deleteTask(todo.id)"
              class="btn btn-sm btn-danger"
            >
              🗑️
            </button>
          </div>
        </div>
      </div>

      <!-- Mensaje cuando no hay tareas -->
      <div *ngIf="(filteredTodos$ | async)?.length === 0" class="empty-state">
        <p>{{ getEmptyMessage() }}</p>
      </div>

      <!-- Modal de edición -->
      <div *ngIf="editingTodo" class="modal-overlay" (click)="cancelEdit()">
        <div class="modal" (click)="$event.stopPropagation()">
          <h3>Editar Tarea</h3>
          <input 
            #editInput
            type="text" 
            [value]="editingTodo.text"
            class="form-control"
          >
          <div class="modal-actions">
            <button 
              (click)="saveEdit(editInput.value)"
              class="btn btn-success"
            >
              💾 Guardar
            </button>
            <button 
              (click)="cancelEdit()"
              class="btn btn-secondary"
            >
              ❌ Cancelar
            </button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .todo-container {
      max-width: 800px;
      margin: 20px auto;
      padding: 20px;
      background-color: #f5f5f5;
      border-radius: 8px;
    }

    .add-task-form {
      display: flex;
      margin-bottom: 20px;
      gap: 10px;
    }

    .task-input {
      flex: 1;
      padding: 10px;
      border: 1px solid #ddd;
      border-radius: 4px;
      font-size: 14px;
    }

    .filters {
      display: flex;
      gap: 10px;
      margin-bottom: 20px;
    }

    .btn {
      padding: 8px 16px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 14px;
    }

    .btn-primary { background-color: #007bff; color: white; }
    .btn-secondary { background-color: #6c757d; color: white; }
    .btn-danger { background-color: #dc3545; color: white; }
    .btn-success { background-color: #28a745; color: white; }
    .btn-filter { background-color: #e9ecef; color: #495057; }
    .btn-filter.active { background-color: #007bff; color: white; }
    .btn-sm { padding: 4px 8px; font-size: 12px; }
    .btn:disabled { opacity: 0.6; cursor: not-allowed; }

    .stats {
      background-color: white;
      padding: 10px;
      border-radius: 4px;
      margin-bottom: 20px;
    }

    .task-list {
      background-color: white;
      border-radius: 4px;
      overflow: hidden;
    }

    .task-item {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 15px;
      border-bottom: 1px solid #eee;
      transition: background-color 0.2s;
    }

    .task-item:hover {
      background-color: #f8f9fa;
    }

    .task-item.completed {
      opacity: 0.7;
      background-color: #f1f3f4;
    }

    .task-content {
      display: flex;
      align-items: center;
      gap: 10px;
      flex: 1;
    }

    .task-checkbox {
      transform: scale(1.2);
    }

    .task-text {
      flex: 1;
      font-size: 16px;
    }

    .task-text.line-through {
      text-decoration: line-through;
    }

    .task-date {
      color: #6c757d;
      font-size: 12px;
    }

    .task-actions {
      display: flex;
      gap: 5px;
    }

    .empty-state {
      text-align: center;
      padding: 40px;
      color: #6c757d;
      font-style: italic;
    }

    .modal-overlay {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.5);
      display: flex;
      justify-content: center;
      align-items: center;
      z-index: 1000;
    }

    .modal {
      background-color: white;
      padding: 20px;
      border-radius: 8px;
      min-width: 300px;
    }

    .modal-actions {
      display: flex;
      gap: 10px;
      margin-top: 15px;
      justify-content: flex-end;
    }

    .form-control {
      width: 100%;
      padding: 8px;
      border: 1px solid #ddd;
      border-radius: 4px;
      margin: 10px 0;
    }
  `]
})
export class TodoListComponent implements OnInit {
  // Prompt: Usar BehaviorSubject para manejo de estado reactivo
  // Debe permitir emisión de nuevos valores y subscripción a cambios
  private todosSubject = new BehaviorSubject<Todo[]>([]);
  todos$ = this.todosSubject.asObservable();

  private filterSubject = new BehaviorSubject<FilterType>('all');
  currentFilter: FilterType = 'all';

  editingTodo: Todo | null = null;

  // Prompt: Configurar opciones de filtro con labels y valores
  filterOptions = [
    { label: '📋 Todas', value: 'all' as FilterType },
    { label: '⏳ Pendientes', value: 'pending' as FilterType },
    { label: '✅ Completadas', value: 'completed' as FilterType }
  ];

  // Prompt: Crear observables derivados para estadísticas
  // Usar operadores RxJS para calcular contadores en tiempo real
  completedCount$ = this.todos$.pipe(
    map(todos => todos.filter(todo => todo.completed).length)
  );

  pendingCount$ = this.todos$.pipe(
    map(todos => todos.filter(todo => !todo.completed).length)
  );

  // Prompt: Observable para tareas filtradas según el filtro actual
  filteredTodos$ = this.todos$.pipe(
    map(todos => {
      switch (this.currentFilter) {
        case 'completed':
          return todos.filter(todo => todo.completed);
        case 'pending':
          return todos.filter(todo => !todo.completed);
        default:
          return todos;
      }
    })
  );

  ngOnInit(): void {
    // Prompt: Inicializar con datos de ejemplo
    // Crear array de tareas con diferentes estados
    this.initializeSampleData();
  }

  /**
   * Prompt: Método para agregar nueva tarea
   * Debe validar texto no vacío y crear tarea con ID único
   */
  addTask(text: string): void {
    if (text.trim()) {
      const newTodo: Todo = {
        id: this.generateId(),
        text: text.trim(),
        completed: false,
        createdAt: new Date()
      };

      const currentTodos = this.todosSubject.value;
      this.todosSubject.next([...currentTodos, newTodo]);
    }
  }

  /**
   * Prompt: Método para alternar estado completado de tarea
   * Debe encontrar tarea por ID y cambiar su estado
   */
  toggleTask(id: string): void {
    const currentTodos = this.todosSubject.value;
    const updatedTodos = currentTodos.map(todo =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    );
    this.todosSubject.next(updatedTodos);
  }

  /**
   * Prompt: Método para eliminar tarea
   * Debe filtrar array removiendo tarea con ID específico
   */
  deleteTask(id: string): void {
    const currentTodos = this.todosSubject.value;
    const filteredTodos = currentTodos.filter(todo => todo.id !== id);
    this.todosSubject.next(filteredTodos);
  }

  /**
   * Prompt: Método para iniciar edición de tarea
   * Debe establecer tarea en estado de edición
   */
  editTask(todo: Todo): void {
    this.editingTodo = { ...todo };
  }

  /**
   * Prompt: Método para guardar edición de tarea
   * Debe actualizar texto y salir del modo edición
   */
  saveEdit(newText: string): void {
    if (this.editingTodo && newText.trim()) {
      const currentTodos = this.todosSubject.value;
      const updatedTodos = currentTodos.map(todo =>
        todo.id === this.editingTodo!.id 
          ? { ...todo, text: newText.trim() }
          : todo
      );
      this.todosSubject.next(updatedTodos);
      this.editingTodo = null;
    }
  }

  /**
   * Prompt: Método para cancelar edición
   * Debe limpiar estado de edición sin guardar cambios
   */
  cancelEdit(): void {
    this.editingTodo = null;
  }

  /**
   * Prompt: Método para establecer filtro activo
   * Debe actualizar filtro actual y filtrar tareas mostradas
   */
  setFilter(filter: FilterType): void {
    this.currentFilter = filter;
  }

  /**
   * Prompt: Función para trackBy en ngFor
   * Debe retornar identificador único para optimizar renderizado
   */
  trackByTodo(index: number, todo: Todo): string {
    return todo.id;
  }

  /**
   * Prompt: Método para obtener mensaje cuando no hay tareas
   * Debe retornar mensaje contextual según el filtro activo
   */
  getEmptyMessage(): string {
    switch (this.currentFilter) {
      case 'completed':
        return '🎉 ¡No hay tareas completadas aún!';
      case 'pending':
        return '✨ ¡Todas las tareas están completadas!';
      default:
        return '📝 No hay tareas. ¡Agrega una nueva tarea para comenzar!';
    }
  }

  /**
   * Prompt: Método privado para generar ID único
   * Debe retornar string único basado en timestamp y random
   */
  private generateId(): string {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
  }

  /**
   * Prompt: Método privado para inicializar datos de ejemplo
   * Debe crear varias tareas con diferentes estados y fechas
   */
  private initializeSampleData(): void {
    const sampleTodos: Todo[] = [
      {
        id: this.generateId(),
        text: 'Aprender Angular con GitHub Copilot',
        completed: true,
        createdAt: new Date(Date.now() - 86400000) // Ayer
      },
      {
        id: this.generateId(),
        text: 'Crear componente de perfil de usuario',
        completed: false,
        createdAt: new Date(Date.now() - 3600000) // Hace 1 hora
      },
      {
        id: this.generateId(),
        text: 'Implementar validación de formularios',
        completed: false,
        createdAt: new Date() // Ahora
      }
    ];

    this.todosSubject.next(sampleTodos);
  }
}

/**
 * Prompt: Interface para definir estructura de tarea
 * Debe incluir ID único, texto, estado y fecha de creación
 */
export interface Todo {
  id: string;
  text: string;
  completed: boolean;
  createdAt: Date;
}

/**
 * Prompt: Tipo para filtros de tareas
 * Debe incluir opciones: todas, pendientes, completadas
 */
export type FilterType = 'all' | 'pending' | 'completed';
