// examples/react/basic/UserProfile.tsx
import React, { useState, useEffect, useCallback } from 'react';

/**
 * Prompt: Componente React funcional para mostrar y editar perfil de usuario
 * Debe usar hooks (useState, useEffect, useCallback), validación y manejo de estado
 * Implementar modo vista y edición con formulario controlado
 */

interface User {
  name: string;
  email: string;
  age: number;
  department: string;
}

interface UserProfileProps {
  initialUser: User;
  onUserUpdated: (user: User) => void;
  onEditingCancelled: () => void;
}

interface FormErrors {
  name?: string;
  email?: string;
  age?: string;
  department?: string;
}

const UserProfile: React.FC<UserProfileProps> = ({
  initialUser,
  onUserUpdated,
  onEditingCancelled,
}) => {
  // Prompt: Definir estados usando useState hook
  // Incluir estado para modo edición, datos del formulario y errores
  const [isEditing, setIsEditing] = useState(false);
  const [formData, setFormData] = useState<User>(initialUser);
  const [errors, setErrors] = useState<FormErrors>({});
  const [hasChanges, setHasChanges] = useState(false);

  // Prompt: useEffect para detectar cambios en initialUser
  // Debe sincronizar formData cuando cambie el usuario inicial
  useEffect(() => {
    setFormData(initialUser);
    setHasChanges(false);
  }, [initialUser]);

  // Prompt: useEffect para detectar cambios en el formulario
  // Debe comparar formData con initialUser para establecer hasChanges
  useEffect(() => {
    const hasFormChanges = JSON.stringify(formData) !== JSON.stringify(initialUser);
    setHasChanges(hasFormChanges);
  }, [formData, initialUser]);

  /**
   * Prompt: Función de validación usando useCallback
   * Debe validar todos los campos y retornar objeto con errores
   */
  const validateForm = useCallback((): FormErrors => {
    const newErrors: FormErrors = {};

    // Validación del nombre
    if (!formData.name.trim()) {
      newErrors.name = 'El nombre es requerido';
    } else if (formData.name.trim().length < 2) {
      newErrors.name = 'El nombre debe tener al menos 2 caracteres';
    }

    // Validación del email
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!formData.email.trim()) {
      newErrors.email = 'El email es requerido';
    } else if (!emailRegex.test(formData.email)) {
      newErrors.email = 'Ingrese un email válido';
    }

    // Validación de la edad
    if (!formData.age || formData.age < 18 || formData.age > 120) {
      newErrors.age = 'La edad debe estar entre 18 y 120 años';
    }

    // Validación del departamento
    if (!formData.department) {
      newErrors.department = 'Debe seleccionar un departamento';
    }

    return newErrors;
  }, [formData]);

  /**
   * Prompt: Función para manejar cambios en inputs usando useCallback
   * Debe actualizar formData y limpiar errores del campo modificado
   */
  const handleInputChange = useCallback((
    field: keyof User,
    value: string | number
  ) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));

    // Limpiar error del campo si existe
    if (errors[field]) {
      setErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[field];
        return newErrors;
      });
    }
  }, [errors]);

  /**
   * Prompt: Función para habilitar modo edición
   * Debe limpiar errores y establecer isEditing en true
   */
  const handleEnableEditing = useCallback(() => {
    setIsEditing(true);
    setErrors({});
  }, []);

  /**
   * Prompt: Función para cancelar edición
   * Debe resetear formData, errores y cambiar a modo vista
   */
  const handleCancelEditing = useCallback(() => {
    setFormData(initialUser);
    setErrors({});
    setIsEditing(false);
    setHasChanges(false);
    onEditingCancelled();
  }, [initialUser, onEditingCancelled]);

  /**
   * Prompt: Función para manejar envío del formulario
   * Debe validar, y si es válido, emitir evento con usuario actualizado
   */
  const handleSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    
    const validationErrors = validateForm();
    setErrors(validationErrors);

    if (Object.keys(validationErrors).length === 0) {
      onUserUpdated(formData);
      setIsEditing(false);
      setHasChanges(false);
      console.log('Usuario actualizado:', formData);
    }
  }, [formData, validateForm, onUserUpdated]);

  // Prompt: Lista de opciones para el select de departamento
  const departmentOptions = [
    { value: '', label: 'Seleccionar departamento' },
    { value: 'Engineering', label: 'Ingeniería' },
    { value: 'Marketing', label: 'Marketing' },
    { value: 'Sales', label: 'Ventas' },
    { value: 'HR', label: 'Recursos Humanos' },
    { value: 'Finance', label: 'Finanzas' },
  ];

  // Prompt: CSS-in-JS styles usando objeto de estilos
  const styles: { [key: string]: React.CSSProperties } = {
    container: {
      maxWidth: '600px',
      margin: '20px auto',
      padding: '20px',
      border: '1px solid #ddd',
      borderRadius: '8px',
      backgroundColor: '#f9f9f9',
      fontFamily: 'Arial, sans-serif',
    },
    profileInfo: {
      marginBottom: '20px',
    },
    profileItem: {
      margin: '8px 0',
      padding: '8px',
      backgroundColor: 'white',
      borderRadius: '4px',
    },
    form: {
      display: 'flex',
      flexDirection: 'column',
      gap: '15px',
    },
    formGroup: {
      display: 'flex',
      flexDirection: 'column',
    },
    label: {
      marginBottom: '5px',
      fontWeight: 'bold',
      color: '#333',
    },
    input: {
      padding: '8px 12px',
      border: '1px solid #ccc',
      borderRadius: '4px',
      fontSize: '14px',
    },
    inputError: {
      padding: '8px 12px',
      border: '1px solid #dc3545',
      borderRadius: '4px',
      fontSize: '14px',
    },
    select: {
      padding: '8px 12px',
      border: '1px solid #ccc',
      borderRadius: '4px',
      fontSize: '14px',
    },
    error: {
      color: '#dc3545',
      fontSize: '12px',
      marginTop: '4px',
    },
    buttonGroup: {
      display: 'flex',
      gap: '10px',
      marginTop: '20px',
    },
    button: {
      padding: '8px 16px',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      fontSize: '14px',
    },
    primaryButton: {
      backgroundColor: '#007bff',
      color: 'white',
    },
    successButton: {
      backgroundColor: '#28a745',
      color: 'white',
    },
    secondaryButton: {
      backgroundColor: '#6c757d',
      color: 'white',
    },
    disabledButton: {
      opacity: 0.6,
      cursor: 'not-allowed',
    },
    changesIndicator: {
      color: '#ffc107',
      fontSize: '12px',
      fontStyle: 'italic',
      marginTop: '5px',
    },
  };

  return (
    <div style={styles.container}>
      <h2>👤 Perfil de Usuario</h2>
      
      {!isEditing ? (
        // Modo vista
        <div>
          <div style={styles.profileInfo}>
            <div style={styles.profileItem}>
              <strong>Nombre:</strong> {initialUser.name}
            </div>
            <div style={styles.profileItem}>
              <strong>Email:</strong> {initialUser.email}
            </div>
            <div style={styles.profileItem}>
              <strong>Edad:</strong> {initialUser.age}
            </div>
            <div style={styles.profileItem}>
              <strong>Departamento:</strong> {initialUser.department}
            </div>
          </div>
          <button
            onClick={handleEnableEditing}
            style={{ ...styles.button, ...styles.primaryButton }}
          >
            ✏️ Editar Perfil
          </button>
        </div>
      ) : (
        // Modo edición
        <form onSubmit={handleSubmit} style={styles.form}>
          <div style={styles.formGroup}>
            <label htmlFor="name" style={styles.label}>
              Nombre:
            </label>
            <input
              id="name"
              type="text"
              value={formData.name}
              onChange={(e) => handleInputChange('name', e.target.value)}
              style={errors.name ? styles.inputError : styles.input}
            />
            {errors.name && <div style={styles.error}>{errors.name}</div>}
          </div>

          <div style={styles.formGroup}>
            <label htmlFor="email" style={styles.label}>
              Email:
            </label>
            <input
              id="email"
              type="email"
              value={formData.email}
              onChange={(e) => handleInputChange('email', e.target.value)}
              style={errors.email ? styles.inputError : styles.input}
            />
            {errors.email && <div style={styles.error}>{errors.email}</div>}
          </div>

          <div style={styles.formGroup}>
            <label htmlFor="age" style={styles.label}>
              Edad:
            </label>
            <input
              id="age"
              type="number"
              value={formData.age}
              onChange={(e) => handleInputChange('age', parseInt(e.target.value) || 0)}
              style={errors.age ? styles.inputError : styles.input}
            />
            {errors.age && <div style={styles.error}>{errors.age}</div>}
          </div>

          <div style={styles.formGroup}>
            <label htmlFor="department" style={styles.label}>
              Departamento:
            </label>
            <select
              id="department"
              value={formData.department}
              onChange={(e) => handleInputChange('department', e.target.value)}
              style={errors.department ? { ...styles.select, borderColor: '#dc3545' } : styles.select}
            >
              {departmentOptions.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
            {errors.department && <div style={styles.error}>{errors.department}</div>}
          </div>

          {hasChanges && (
            <div style={styles.changesIndicator}>
              ⚠️ Hay cambios sin guardar
            </div>
          )}

          <div style={styles.buttonGroup}>
            <button
              type="submit"
              disabled={Object.keys(errors).length > 0}
              style={{
                ...styles.button,
                ...styles.successButton,
                ...(Object.keys(errors).length > 0 ? styles.disabledButton : {}),
              }}
            >
              💾 Guardar Cambios
            </button>
            <button
              type="button"
              onClick={handleCancelEditing}
              style={{ ...styles.button, ...styles.secondaryButton }}
            >
              ❌ Cancelar
            </button>
          </div>
        </form>
      )}
    </div>
  );
};

export default UserProfile;

// examples/angular/basic/user-profile.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

/**
 * Prompt: Componente Angular para mostrar y editar perfil de usuario
 * Debe incluir validación de formularios, eventos y manejo de estado
 * Usar reactive forms y validadores personalizados
 */
@Component({
  selector: 'app-user-profile',
  template: `
    <div class="user-profile-container">
      <h2>👤 Perfil de Usuario</h2>
      
      <!-- Modo vista -->
      <div *ngIf="!isEditing" class="profile-view">
        <div class="profile-info">
          <p><strong>Nombre:</strong> {{ user.name }}</p>
          <p><strong>Email:</strong> {{ user.email }}</p>
          <p><strong>Edad:</strong> {{ user.age }}</p>
          <p><strong>Departamento:</strong> {{ user.department }}</p>
        </div>
        <button (click)="enableEditing()" class="btn btn-primary">
          ✏️ Editar Perfil
        </button>
      </div>

      <!-- Modo edición -->
      <form *ngIf="isEditing" [formGroup]="profileForm" (ngSubmit)="onSubmit()" class="profile-form">
        <div class="form-group">
          <label for="name">Nombre:</label>
          <input 
            id="name" 
            type="text" 
            formControlName="name"
            class="form-control"
            [class.is-invalid]="isFieldInvalid('name')"
          >
          <div *ngIf="isFieldInvalid('name')" class="invalid-feedback">
            El nombre es requerido y debe tener al menos 2 caracteres
          </div>
        </div>

        <div class="form-group">
          <label for="email">Email:</label>
          <input 
            id="email" 
            type="email" 
            formControlName="email"
            class="form-control"
            [class.is-invalid]="isFieldInvalid('email')"
          >
          <div *ngIf="isFieldInvalid('email')" class="invalid-feedback">
            Ingrese un email válido
          </div>
        </div>

        <div class="form-group">
          <label for="age">Edad:</label>
          <input 
            id="age" 
            type="number" 
            formControlName="age"
            class="form-control"
            [class.is-invalid]="isFieldInvalid('age')"
          >
          <div *ngIf="isFieldInvalid('age')" class="invalid-feedback">
            La edad debe estar entre 18 y 120 años
          </div>
        </div>

        <div class="form-group">
          <label for="department">Departamento:</label>
          <select 
            id="department" 
            formControlName="department"
            class="form-control"
            [class.is-invalid]="isFieldInvalid('department')"
          >
            <option value="">Seleccionar departamento</option>
            <option value="Engineering">Ingeniería</option>
            <option value="Marketing">Marketing</option>
            <option value="Sales">Ventas</option>
            <option value="HR">Recursos Humanos</option>
            <option value="Finance">Finanzas</option>
          </select>
          <div *ngIf="isFieldInvalid('department')" class="invalid-feedback">
            Debe seleccionar un departamento
          </div>
        </div>

        <div class="form-actions">
          <button type="submit" [disabled]="profileForm.invalid" class="btn btn-success">
            💾 Guardar Cambios
          </button>
          <button type="button" (click)="cancelEditing()" class="btn btn-secondary">
            ❌ Cancelar
          </button>
        </div>
      </form>
    </div>
  `,
  styles: [`
    .user-profile-container {
      max-width: 600px;
      margin: 20px auto;
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 8px;
      background-color: #f9f9f9;
    }

    .profile-info {
      margin-bottom: 20px;
    }

    .profile-info p {
      margin: 8px 0;
      padding: 8px;
      background-color: white;
      border-radius: 4px;
    }

    .form-group {
      margin-bottom: 15px;
    }

    .form-control {
      width: 100%;
      padding: 8px 12px;
      border: 1px solid #ccc;
      border-radius: 4px;
      font-size: 14px;
    }

    .form-control.is-invalid {
      border-color: #dc3545;
    }

    .invalid-feedback {
      color: #dc3545;
      font-size: 12px;
      margin-top: 4px;
    }

    .btn {
      padding: 8px 16px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      margin-right: 10px;
    }

    .btn-primary { background-color: #007bff; color: white; }
    .btn-success { background-color: #28a745; color: white; }
    .btn-secondary { background-color: #6c757d; color: white; }
    .btn:disabled { opacity: 0.6; cursor: not-allowed; }

    .form-actions {
      margin-top: 20px;
    }
  `]
})
export class UserProfileComponent implements OnInit {
  @Input() user: User = {
    name: '',
    email: '',
    age: 0,
    department: ''
  };

  @Output() userUpdated = new EventEmitter<User>();
  @Output() editingCancelled = new EventEmitter<void>();

  profileForm: FormGroup;
  isEditing = false;

  constructor(private formBuilder: FormBuilder) {
    // Prompt: Crear formulario reactivo con validadores
    // Incluir validaciones personalizadas para edad y email
    this.profileForm = this.formBuilder.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      email: ['', [Validators.required, Validators.email]],
      age: ['', [Validators.required, Validators.min(18), Validators.max(120)]],
      department: ['', Validators.required]
    });
  }

  ngOnInit(): void {
    // Prompt: Inicializar formulario con valores del usuario
    // Usar patchValue para establecer valores iniciales
    this.updateFormValues();
  }

  /**
   * Prompt: Método para habilitar modo edición
   * Debe actualizar los valores del formulario con los datos actuales del usuario
   */
  enableEditing(): void {
    this.isEditing = true;
    this.updateFormValues();
  }

  /**
   * Prompt: Método para cancelar edición
   * Debe resetear el formulario y volver al modo vista
   */
  cancelEditing(): void {
    this.isEditing = false;
    this.profileForm.reset();
    this.updateFormValues();
    this.editingCancelled.emit();
  }

  /**
   * Prompt: Método para manejar envío del formulario
   * Debe validar datos y emitir evento con usuario actualizado
   */
  onSubmit(): void {
    if (this.profileForm.valid) {
      const updatedUser: User = {
        ...this.user,
        ...this.profileForm.value
      };
      
      this.user = updatedUser;
      this.isEditing = false;
      this.userUpdated.emit(updatedUser);
      
      console.log('Usuario actualizado:', updatedUser);
    }
  }

  /**
   * Prompt: Método para verificar si un campo tiene errores
   * Debe retornar true si el campo es inválido y ha sido tocado
   */
  isFieldInvalid(fieldName: string): boolean {
    const field = this.profileForm.get(fieldName);
    return !!(field && field.invalid && (field.dirty || field.touched));
  }

  /**
   * Prompt: Método privado para actualizar valores del formulario
   * Debe usar patchValue para sincronizar con el objeto user
   */
  private updateFormValues(): void {
    this.profileForm.patchValue({
      name: this.user.name,
      email: this.user.email,
      age: this.user.age,
      department: this.user.department
    });
  }
}

/**
 * Prompt: Interface para definir estructura del usuario
 * Debe incluir propiedades básicas con tipos explícitos
 */
export interface User {
  name: string;
  email: string;
  age: number;
  department: string;
}
